name: Build

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 태그가 push될 때 실행

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      shell: bash
      run: poetry install
    
    - name: Convert icons
      shell: bash
      run: poetry run python scripts/convert_icon.py
    
    - name: Build with PyInstaller
      shell: bash
      run: poetry run python build.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wordiff-${{ matrix.os }}
        path: |
          dist/**/*
        if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          artifacts/wordiff-windows-latest/dist/windows/wordiff.exe
          artifacts/wordiff-macos-latest/dist/darwin/wordiff
          artifacts/wordiff-ubuntu-latest/dist/linux/wordiff
        draft: false
        prerelease: false
        generate_release_notes: true 