name: Build

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 태그가 push될 때 실행

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
        ]
        python-version: ['3.9']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      shell: bash
      run: poetry install
    
    - name: Convert icons
      shell: bash
      run: poetry run python scripts/convert_icon.py
    
    - name: Build with PyInstaller
      shell: bash
      run: poetry run python build.py
      env:
        PYTHONOPTIMIZE: 1  # 최적화 활성화
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wordiff-${{ matrix.os }}
        path: dist/**/*
        if-no-files-found: error
        retention-days: 5  # 아티팩트 보관 기간 설정

  release:
    needs: [build]  # 데스크톱 빌드만 기다림
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
      
    - name: List files
      run: |
        echo "Downloaded artifacts:"
        ls -R artifacts/
        find artifacts/ -type f
      
    - name: 파일들을 릴리스용 디렉토리로 복사
      run: |
        mkdir -p release
        cp artifacts/wordiff-windows-latest/windows/wordiff.exe release/wordiff-windows.exe
        cp artifacts/wordiff-ubuntu-latest/linux/wordiff release/wordiff-linux
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          release/wordiff-windows.exe
          release/wordiff-linux
          draft: false
          prerelease: false
          generate_release_notes: true 

  android-build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython==0.29.33
    
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: stable
        command: buildozer android debug -v
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wordiff-android
        path: ${{ steps.buildozer.outputs.filename }}
        if-no-files-found: error 